<footer class="footer" role="contentinfo">
	<div class="footer-top">
		<div class="container">
			<div class="footer-contact">
				<div itemscope="" itemtype="http://schema.org/Organization">
					<h3 itemprop="name">University of Iowa Museum of Art</h3>
					<p><strong><a href="http://hulk.imu.uiowa.edu/uima/visit/locations/">View Museum Locations</a></strong></p>
					<p itemprop="telephone"><span><span id="gc-number-0" class="gc-cs-link" title="Call with Google Voice">319-335-1727</span></span><br>
					<a itemprop="email" href="mailto:uima@uiowa.edu">uima@uiowa.edu</a>
					</p>
					<p><small>© 2015 University of Iowa Museum of Art.<br>All Rights Reserved. <a href="http://www.uiowa.edu/homepage/online-privacy-information">Privacy Policy</a></small></p>
					
				</div>
			</div>
			<div class="clearfix footer-links">
				<div class="main-links">
					<ul class="">
						<li><a href="http://hulk.imu.uiowa.edu/uima/">Home</a></li>
						
							<li><a href="/uima/visit/">Visit</a></li>
						
							<li><a href="/uima/exhibitions/">Exhibitions</a></li>
						
							<li><a href="/uima/collections/">Collections</a></li>
						
					</ul>
					<ul class="">
						
							<li><a href="/uima/education/">Education</a></li>
						
							<li><a href="/uima/events/">Events</a></li>
						
							<li><a href="/uima/about/">About</a></li>
						
							<li><a href="/uima/support/">Support</a></li>
						
					</ul>
				</div>
				<ul class="secondary">
					<li><a href="http://hulk.imu.uiowa.edu/uima/about/contact/">Contact</a></li>
					<li><a href="http://hulk.imu.uiowa.edu/uima/support/membership/">Membership</a></li>
					<li><a href="http://hulk.imu.uiowa.edu/uima/about/shop/">Shop</a></li>
					<li><a href="http://hulk.imu.uiowa.edu/uima/about/news/">News / Press</a></li>
				</ul>
			</div>
		</div><!-- end .container -->
	</div>
	<div class="footer-bottom">
		<div class="container">
			<div id="newsletter" class="clearfix">
				<form name="ccoptin" action="http://ui.constantcontact.com/d.jsp" target="_blank" method="post">
					<label for="cc_email">Sign up for our Newsletter:</label>
					<input type="text" name="ea" size="20" class="text" value="E-mail Address" id="cc_email">
					<input type="submit" name="go" value="Sign Up" class="submit">
					<input type="hidden" name="m" value="1101515594689">
					<input type="hidden" name="p" value="oi">
				</form>
			</div>
			<ul class="clearfix social-icons">
				
					<li>
						<a href="https://www.facebook.com/UIMuseumofArt" title="Facebook" target="_blank">
							<img src="/images/facebook_circle_gray-32.png" alt="Facebook">
						</a>
					</li>
				
				
					<li>
						<a href="https://twitter.com/UIMuseumofArt" title="Twitter" target="_blank">
							<img src="/images/twitter_circle_gray-32.png" alt="Twitter">
						</a>
					</li>
				
				
					<li>
						<a href="https://www.youtube.com/user/UIMAartmatters" title="Youtube" target="_blank">
							<img src="/images/youtube_circle_gray-32.png" alt="YouTube">
						</a>
					</li>
				
			</ul>

			<div class="clearfix footer-logos">
				<a href="http://www.uiowa.edu">
					<img src="/images/uiowalogo.gif" alt="University of Iowa">
				</a>
				<a href="http://www.uima.uiowa.edu">
					<img src="/images/iowamuseum_logo.gif" alt="University of Iowa Museum of Art">
				</a>
			</div>

		</div>
	</div>
</footer>