
<header class="header" role="banner">
	<div class="container">

		<a href="http://uima.uiowa.edu/" class="logo">
			<img src="/images/uima_logo.png" alt="University of Iowa Museum of Art">
		</a>

		<!-- Search -->
		
			<div class="search-bar mobile-hide" role="search">
			  <form id="SearchForm_SearchForm" action="http://uima.uiowa.edu/home/SearchForm" method="get" enctype="application/x-www-form-urlencoded">
	<p id="SearchForm_SearchForm_error" class="message " style="display: none"></p>
	<fieldset>
		<div id="Search" class="field text nolabel">
			<div class="middleColumn">
				<label for="SearchForm_SearchForm_Search" class="visuallyhidden">Search</label>
				<input type="text" name="Search" value="" placeholder="Search" class="text nolabel" id="SearchForm_SearchForm_Search">
			</div>
		</div>
		<input type="submit" name="action_results" value="Go" class="action" id="SearchForm_SearchForm_action_results">
	</fieldset>
</form>
			</div>
		

		<span class="shifter-handle">Menu</span>
		<nav role="navigation" class="nav-wrapper no-print" aria-label="Main menu">
	<ul class="main-nav clearfix" role="menubar" aria-hidden="false">
		
			<li class="first parent" role="menuitem" aria-haspopup="true"><a href="http://uima.uiowa.edu/visit/">Visit</a>

				

			</li>
		
			<li class=" parent" role="menuitem" aria-haspopup="true"><a href="http://uima.uiowa.edu/exhibitions/">Exhibitions</a>

				
					<ul data-test="true" aria-hidden="true" role="menu">
						<li role="menuitem"><a href="http://uima.uiowa.edu/exhibitions/" tabindex="-1">Current</a></li>
						<li role="menuitem"><a href="http://uima.uiowa.edu/exhibitions/upcoming" tabindex="-1">Upcoming</a></li>
						<li role="menuitem"><a href="http://uima.uiowa.edu/exhibitions/past" tabindex="-1">Past</a></li>
					</ul>

				

			</li>
		
			<li class=" parent" role="menuitem" aria-haspopup="true"><a href="http://uima.uiowa.edu/collections/">Collections</a>

			
				

			</li>
		
			<li class=" parent" role="menuitem" aria-haspopup="true"><a href="http://uima.uiowa.edu/education/">Education</a>

				

				

			</li>
		
			<li class=" parent" role="menuitem" aria-haspopup="true"><a href="http://uima.uiowa.edu/events/">Events</a>


				

			</li>
		
			<li class=" parent" role="menuitem" aria-haspopup="true"><a href="http://uima.uiowa.edu/about/">About</a>

				

				

			</li>
		
			<li class="last parent" role="menuitem" aria-haspopup="true"><a href="http://uima.uiowa.edu/support/">Support</a>


				

			</li>
		
	</ul>
</nav>
	</div>
</header>