
<header class="header" role="banner">
	<div class="container">

		<a href="http://uima.uiowa.edu/" class="logo">
			<img src="/images/uima_logo.png" alt="University of Iowa Museum of Art">
		</a>

		<!-- Search -->
		
			<div class="search-bar mobile-hide" role="search">
			  <form id="SearchForm_SearchForm" action="http://uima.uiowa.edu/home/SearchForm" method="get" enctype="application/x-www-form-urlencoded">
	<p id="SearchForm_SearchForm_error" class="message " style="display: none"></p>
	<fieldset>
		<div id="Search" class="field text nolabel">
			<div class="middleColumn">
				<label for="SearchForm_SearchForm_Search" class="visuallyhidden">Search</label>
				<input type="text" name="Search" value="" placeholder="Search" class="text nolabel" id="SearchForm_SearchForm_Search">
			</div>
		</div>
		<input type="submit" name="action_results" value="Go" class="action" id="SearchForm_SearchForm_action_results">
	</fieldset>
</form>
			</div>
		

		<span class="shifter-handle">Menu</span>
		<nav role="navigation" class="nav-wrapper no-print" aria-label="Main menu">
	<ul class="main-nav clearfix" role="menubar" aria-hidden="false">
		
			<li class="first parent" role="menuitem" aria-haspopup="true"><a href="http://uima.uiowa.edu/visit/">Visit</a>

				
					<ul data-test="true" aria-hidden="false" role="menu" class="">
						
							<li class="first " role="menuitem"><a href="http://uima.uiowa.edu/visit/locations/" tabindex="0">Locations</a></li>
						
							<li class=" " role="menuitem"><a href="http://uima.uiowa.edu/visit/group-tours-class-visits/" tabindex="0">Group Tours / Class Visits</a></li>
						
							<li class="last " role="menuitem"><a href="http://uima.uiowa.edu/visit/visitors-with-special-needs/" tabindex="0">Visitors with special needs</a></li>
						
					</ul>
				

			</li>
		
			<li class=" parent" role="menuitem" aria-haspopup="true"><a href="http://uima.uiowa.edu/exhibitions/">Exhibitions</a>

				
					<ul data-test="true" aria-hidden="true" role="menu">
						<li role="menuitem"><a href="http://uima.uiowa.edu/exhibitions/" tabindex="-1">Current</a></li>
						<li role="menuitem"><a href="http://uima.uiowa.edu/exhibitions/upcoming" tabindex="-1">Upcoming</a></li>
						<li role="menuitem"><a href="http://uima.uiowa.edu/exhibitions/past" tabindex="-1">Past</a></li>
					</ul>

				

			</li>
		
			<li class=" parent" role="menuitem" aria-haspopup="true"><a href="http://uima.uiowa.edu/collections/">Collections</a>

				
					<ul data-test="true" aria-hidden="true" role="menu">
						
							<li class="first " role="menuitem"><a href="http://uima.uiowa.edu/collections/european-art-1900-1980/" tabindex="-1">European Art 1900-1980</a></li>
						
							<li class=" " role="menuitem"><a href="http://uima.uiowa.edu/collections/american-art-1900-1980/" tabindex="-1">American Art 1900-1980</a></li>
						
							<li class=" " role="menuitem"><a href="http://uima.uiowa.edu/collections/contemporary-art/" tabindex="-1">Contemporary Art</a></li>
						
							<li class=" " role="menuitem"><a href="http://uima.uiowa.edu/collections/african-art/" tabindex="-1">African Art</a></li>
						
							<li class=" " role="menuitem"><a href="http://uima.uiowa.edu/collections/works-on-paper-before-1900/" tabindex="-1">Works on Paper before 1900</a></li>
						
							<li class=" " role="menuitem"><a href="http://uima.uiowa.edu/collections/european-and-american-prints-drawings-photographs-1900-1970/" tabindex="-1">European and American Prints, Drawings, Photographs 1900-1980</a></li>
						
							<li class=" " role="menuitem"><a href="http://uima.uiowa.edu/collections/arts-of-the-ancient-americas-and-native-america/" tabindex="-1">Arts of the Ancient Americas and Native America</a></li>
						
							<li class=" " role="menuitem"><a href="http://uima.uiowa.edu/collections/ceramics/" tabindex="-1">Ceramics</a></li>
						
							<li class=" " role="menuitem"><a href="http://uima.uiowa.edu/collections/metal-arts/" tabindex="-1">Metal Arts</a></li>
						
							<li class=" " role="menuitem"><a href="http://uima.uiowa.edu/collections/asian-art/" tabindex="-1">Asian Art</a></li>
						
							<li class=" " role="menuitem"><a href="http://uima.uiowa.edu/collections/iowa-artists/" tabindex="-1">Iowa Artists</a></li>
						
							<li class=" " role="menuitem"><a href="http://uima.uiowa.edu/collections/iowa-gallery-digitized-art-collections/" tabindex="-1">Iowa Gallery: Digitized Art Collections</a></li>
						
							<li class="last " role="menuitem"><a href="http://uima.uiowa.edu/collections/rights-and-reproductions/" tabindex="-1">Rights and Reproductions</a></li>
						
					</ul>
				

			</li>
		
			<li class=" parent" role="menuitem" aria-haspopup="true"><a href="http://uima.uiowa.edu/education/">Education</a>

				
					<ul data-test="true" aria-hidden="true" role="menu">
						
							<li class="first " role="menuitem"><a href="http://uima.uiowa.edu/education/uima-school-programs/" tabindex="-1">UIMA School Programs</a></li>
						
							<li class=" " role="menuitem"><a href="http://uima.uiowa.edu/education/book-a-uima-school-programs-visit/" tabindex="-1">Book a UIMA School Programs Visit</a></li>
						
							<li class=" " role="menuitem"><a href="http://uima.uiowa.edu/education/book-a-uimaimu-or-black-box-theater-tour-or-visit/" tabindex="-1">Book a UIMA@IMU or Black Box Theater Tour or Visit </a></li>
						
							<li class="last " role="menuitem"><a href="http://uima.uiowa.edu/education/ui-student-research-and-projects/" tabindex="-1">UI Student research and projects</a></li>
						
					</ul>
				

			</li>
		
			<li class=" parent" role="menuitem" aria-haspopup="true"><a href="http://uima.uiowa.edu/events/">Events</a>

				
					<ul data-test="true" aria-hidden="true" role="menu">
						
							<li class="first last " role="menuitem"><a href="http://uima.uiowa.edu/events/past-events/" tabindex="-1">Past Events</a></li>
						
					</ul>
				

			</li>
		
			<li class=" parent" role="menuitem" aria-haspopup="true"><a href="http://uima.uiowa.edu/about/">About</a>

				
					<ul data-test="true" aria-hidden="true" role="menu">
						
							<li class="first " role="menuitem"><a href="http://uima.uiowa.edu/about/letter-from-the-director/" tabindex="-1">Letter from the Director</a></li>
						
							<li class=" " role="menuitem"><a href="http://uima.uiowa.edu/about/history/" tabindex="-1">History</a></li>
						
							<li class=" " role="menuitem"><a href="http://uima.uiowa.edu/about/magazine/" tabindex="-1">Magazine</a></li>
						
							<li class=" " role="menuitem"><a href="http://uima.uiowa.edu/about/artist-books-and-other-publications/" tabindex="-1">Artist books and other publications</a></li>
						
							<li class=" " role="menuitem"><a href="http://uima.uiowa.edu/about/staff/" tabindex="-1">Staff</a></li>
						
							<li class=" " role="menuitem"><a href="http://uima.uiowa.edu/about/contact/" tabindex="-1">Contact</a></li>
						
							<li class=" " role="menuitem"><a href="http://uima.uiowa.edu/about/news/" tabindex="-1">News</a></li>
						
							<li class="last " role="menuitem"><a href="http://uima.uiowa.edu/about/shop/" tabindex="-1">Shop</a></li>
						
					</ul>
				

			</li>
		
			<li class="last parent" role="menuitem" aria-haspopup="true"><a href="http://uima.uiowa.edu/support/">Support</a>

				
					<ul data-test="true" aria-hidden="true" role="menu">
						
							<li class="first " role="menuitem"><a href="http://uima.uiowa.edu/support/volunteer/" tabindex="-1">Volunteer</a></li>
						
							<li class=" " role="menuitem"><a href="http://uima.uiowa.edu/support/make-a-gift/" tabindex="-1">Make a Gift</a></li>
						
							<li class=" " role="menuitem"><a href="http://uima.uiowa.edu/support/membership/" tabindex="-1">Membership</a></li>
						
							<li class="last " role="menuitem"><a href="http://uima.uiowa.edu/support/website-sponsors/" tabindex="-1">Website Sponsors</a></li>
						
					</ul>
				

			</li>
		
	</ul>
</nav>
	</div>
</header>
<!--<div id="page-block">
	<div id="title-banner">
		<a href="http://www.gallerysystems.com" target="_blank"><img src="/graphics/logo1.gif" width="330" height="44" alt="Gallery Systems"/></a>
		<a href="http://www.gallerysystems.com/products/embarkkiosk.html" target="_blank"><img src="/graphics/powered_by.gif" width="120" height="41" alt="Powered by EmbARK Web Kiosk" id="logo-right"/></a>
	</div>

	<div id="left-menu">

		<div class="menu-item"><form name="searchForm" id="searchForm" action="/4DACTION/HANDLECGI/CTN3" method="post">
				<input type="hidden" name="sid" value="{SessionID}"/>
				<input type="hidden" name="SearchType" value="all"/>
				<input type="hidden" name="WholeWord" value="0"/>
				<input type="hidden" name="RefineSearch" value="NewSelection"/>

				<input type="text" name="theKW" size="10" style="background-color: #CCCCCC; width: 85;"/>
				<input type="button" onclick="document.searchForm.submit()" value="search">
		</form></div>

		<div class="menu-item" id="home" onmouseover="menuOn('home');" onmouseout="menuOff('home');" onclick="document.location='/';"><a href="/?sid={SessionId}&x={Sequence}">Home</a></div>

		<div class="menu-item" id="collections" onmouseover="menuOn('collections');" onmouseout="menuOff('collections');" onclick="document.location='/IT_-1?sid={SessionId}&x={Sequence}';"><a href="/IT_-1?sid={SessionId}&x={Sequence}">Browse</a></div>

		<div class="menu-item" id="search" onmouseover="menuOn('search');" onmouseout="menuOff('search');" onclick="document.location='/kiosk/search.htm?sid={SessionId}&x={Sequence}';"><a href="/kiosk/search.htm?sid={SessionId}&x={Sequence}">Search</a></div>

		<div class="menu-item" id="help" onmouseover="menuOn('help');" onmouseout="menuOff('help');"><a href="/kiosk/help.htm" target="_blank">Help</a></div>
-->