<div class="shifter-navigation">
		<div class="mobile-navigation">
			<ul class="">
				
					<li><a href="/uima/visit/" class="link">Visit</a>
					</li>
				
					<li><a href="/uima/exhibitions/" class="link">Exhibitions</a>
					</li>
				
					<li><a href="/uima/collections/" class="link">Collections</a>
					</li>
				
					<li><a href="/uima/education/" class="link">Education</a>
					</li>
				
					<li><a href="/uima/events/" class="link">Events</a>
					</li>
				
					<li class="active"><a href="/uima/about/" class="link">About</a>
					</li>
				
					<li><a href="/uima/support/" class="link">Support</a>
					</li>
				
			</ul>
		</div>
		<!-- <div class="consistent">
			<a href="http://hulk.imu.uiowa.edu/uima/contact" class="link highlight">Contact</a>
			<a href="http://hulk.imu.uiowa.edu/uima/membership" class="link highlight">Membership</a>
		</div> -->
		<!-- Search -->
		
			<div class="search-bar" role="search">
			  <form id="SearchForm_SearchForm" action="http://hulk.imu.uiowa.edu/uima//home/SearchForm" method="get" enctype="application/x-www-form-urlencoded">
	<p id="SearchForm_SearchForm_error" class="message " style="display: none"></p>
	<fieldset>
		<div id="Search" class="field text nolabel">
			<div class="middleColumn">
				<label for="SearchForm_SearchForm_Search" class="visuallyhidden">Search</label>
				<input type="text" name="Search" value="" placeholder="Search" class="text nolabel" id="SearchForm_SearchForm_Search">
			</div>
		</div>
		<input type="submit" name="action_results" value="Go" class="action" id="SearchForm_SearchForm_action_results">
	</fieldset>
</form>
			</div>
		
		<div class="shifter-address">
			<div class="contain">
				<div itemscope="" itemtype="http://schema.org/Organization">
					<h3 itemprop="name">University of Iowa Museum of Art</h3>
					<div itemprop="address" itemscope="" itemtype="http://schema.org/PostalAddress">
						<p><span itemprop="streetAddress">1375 Highway One West<br>1840 Studio Arts Building</span><br><span itemprop="addressLocality">Iowa City, IA</span> <span itemprop="postalCode">52242</span></p>
				</div>
			</div>
		</div>
		<hr>
		<div class="contact">
			<div>
				<a href="mailto:uima@uiowa.edu">uima@uiowa.edu</a>
			</div>
			<div>
				<span><a href="tel:319-335-1727">319-335-1727</a></span>
			</div>
		</div>
	</div>